=== serolyn/ProjetTechnoWeb/XML/merveilles.dtd
<!ELEMENT merveille (identite, description, visite, liens?)>


<!ATTLIST merveille
  id ID #REQUIRED
  type (monument|cite|site|statue) #REQUIRED
  periode (antique|medieval|moderne|mixte) "mixte"
>

<!ELEMENT identite (nom, pays, lieu, coordonnees?)>

<!ELEMENT nom (#PCDATA)>

<!ELEMENT pays (#PCDATA)>
<!ATTLIST pays continent (asie|europe|afrique|amerique|oceanie) #REQUIRED>

<!ELEMENT lieu (#PCDATA)>

<!ELEMENT coordonnees (latitude, longitude)>
<!ELEMENT latitude (#PCDATA)>
<!ELEMENT longitude (#PCDATA)>


<!ELEMENT description (resume, histoire, architecture?, faits?)>
<!ELEMENT resume (#PCDATA)>
<!ELEMENT histoire (#PCDATA)>
<!ELEMENT architecture (#PCDATA)>

<!ELEMENT faits (fait+)>
<!ELEMENT fait (#PCDATA)>
<!ATTLIST fait type (date|dimension|materiau|usage|autre) "autre">

<!ELEMENT visite (etapes, galerie?)>

<!ELEMENT etapes (etape+)>

<!ELEMENT etape (titre, texte, duree?)>
<!ATTLIST etape
  ordre CDATA #REQUIRED
  categorie (intro|contexte|architecture|experience|bonus) #REQUIRED
  difficulte (facile|moyen|difficile) "facile"
  img IDREF #IMPLIED
>

<!ELEMENT titre (#PCDATA)>
<!ELEMENT texte (#PCDATA)>
<!ELEMENT duree (#PCDATA)>


<!ELEMENT galerie (image+)>

<!ELEMENT image (fichier, legende?)>
<!ATTLIST image
  id ID #REQUIRED
  type (photo|plan|carte|illustration) "photo"
>
<!ELEMENT fichier (#PCDATA)>
<!ELEMENT legende (#PCDATA)>
<!ELEMENT liens (lien+)>
<!ELEMENT lien (#PCDATA)>

<!ATTLIST lien type (wiki|unesco|autre) "autre">

=== serolyn/ProjetTechnoWeb/XML/petra.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Fait par Walid BENABDELKRIM EL FILALI-->


<!DOCTYPE merveille SYSTEM "merveilles.dtd">

<merveille id="petra" type="cite" periode="antique">
  <identite>
    <nom>Pétra</nom>
    <pays continent="asie">Jordanie</pays>
    <lieu>Région de Ma’an</lieu>
  </identite>

  <description>
    <resume>Ancienne cité nabatéenne, célèbre pour ses façades monumentales taillées dans le grès.</resume>
    <histoire>Carrefour caravanier majeur, Pétra a prospéré grâce au commerce et à sa maîtrise de l’eau en milieu aride.</histoire>
    <faits>
      <fait type="usage">Fonction historique: ville et centre commercial.</fait>
      <fait type="autre">Particularité: architecture directement sculptée dans la roche.</fait>
    </faits>
  </description>

  <visite>
    <etapes>
      <etape ordre="1" categorie="experience" img="pet01" difficulte="facile">
        <titre>Le Siq</titre>
        <texte>Parcourir la gorge étroite d’accès: l’entrée est déjà une mise en scène.</texte>
        <duree>20 min</duree>
      </etape>

      <etape ordre="2" categorie="contexte" img="pet02" difficulte="moyen">
        <titre>Le Trésor et au-delà</titre>
        <texte>Arrivée sur Al-Khazneh (le “Trésor”), puis progression vers d’autres zones et points de vue.</texte>
        <duree>40 min</duree>
      </etape>
    </etapes>

    <galerie>
      <image id="pet01" type="photo">
        <fichier>petra_01.jpg</fichier>
        <legende>Le Siq (passage d’entrée)</legende>
      </image>
      <image id="pet02" type="photo">
        <fichier>petra_02.jpg</fichier>
        <legende>Al-Khazneh (le Trésor)</legende>
      </image>
    </galerie>
  </visite>

  <liens>
    <lien type="wiki">https://fr.wikipedia.org/wiki/P%C3%A9tra</lien>
  </liens>
</merveille>

=== serolyn/ProjetTechnoWeb/XML/TajMahal.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Fait par Marwa BENSEKKOU-->
<!DOCTYPE merveille SYSTEM "merveilles.dtd">

<merveille id="taj_mahal" type="monument" periode="moderne">
  <identite>
    <nom>Taj Mahal</nom>
    <pays continent="asie">Inde</pays>
    <lieu>Agra (Uttar Pradesh)</lieu>
    <coordonnees>
      <latitude>27.1751</latitude>
      <longitude>78.0421</longitude>
    </coordonnees>
  </identite>

  <description>
    <resume>Mausolée en marbre blanc, symbole de l’architecture moghole et monument funéraire.</resume>
    <histoire>Commandé par l’empereur Shah Jahan en mémoire de Mumtaz Mahal, construit au XVIIe siècle.</histoire>
    <architecture>Plan symétrique, dôme central, marbre blanc et décorations en pierre incrustée.</architecture>
    <faits>
      <fait type="materiau">Matériau principal: marbre blanc.</fait>
      <fait type="usage">Fonction: mausolée (monument funéraire).</fait>
    </faits>
  </description>

  <visite>
    <etapes>
      <etape ordre="1" categorie="intro" img="taj01" difficulte="facile">
        <titre>Entrée et première vue</titre>
        <texte>Découvrir l’axe principal et la perspective: le monument se dévoile progressivement.</texte>
        <duree>10 min</duree>
      </etape>

      <etape ordre="2" categorie="architecture" img="taj02" difficulte="facile">
        <titre>Zoom sur les détails</titre>
        <texte>Observer les motifs, les inscriptions et la symétrie; comprendre la logique du plan.</texte>
        <duree>15 min</duree>
      </etape>
    </etapes>

    <galerie>
      <image id="taj01" type="photo">
        <fichier>taj_01.jpg</fichier>
        <legende>Vue depuis l’axe central</legende>
      </image>
      <image id="taj02" type="photo">
        <fichier>taj_02.jpg</fichier>
        <legende>Détails décoratifs et façade</legende>
      </image>
    </galerie>
  </visite>

  <liens>
    <lien type="wiki">https://fr.wikipedia.org/wiki/Taj_Mahal</lien>
  </liens>
</merveille>
